### ISSUE TITLE
How do you pass the data to the next controller when using the Router?

### ISSUE THREAD

**Issue by ETmanwenhan** [pixeldock/RxSwift-Xcode-Templates#2]
How do you pass the data to the next controller when using the Router?

```swift
class LoginRouter {
    weak var viewController: LoginViewController?

    func navigateToSomewhere() {
        
        //viewController?.navigationController?.pushViewController(nil, animated: true)
    }
}

```

**Comment by pixeldock** [comment]
Thanks for your question! Whenever I have to pass some data to the next Scene I inject the data into the new scene's Builder.

A simple example:
I have a Scene that shows a list of cars (`CarListScene`). When the user taps on a car in the list I want to navigate to a `CarDetailsScene` that shows the details of the selected car. To hand the `carID` to the details Scene I inject it into the `CarDetailsBuilder`:

```
class CarListRouter {
    weak var viewController: CarListViewController?

    func navigateToDetails(withCarID carID: String) {
        let detailsViewController = CarDetailsBuilder.viewController(withCarID: carID)
        viewController?.navigationController?.pushViewController(detailsViewController, animated: true)
    }
}
```

The `CarDetailsBuilder` then injects the data into the `CarDetailsViewModel`:

```
struct CarDetailsBuilder {

    static func viewController(withCarID carID: String) -> UIViewController {
        let viewModel = CarDetailsViewModel(withCarID: carID)
        let router = CarDetailsRouter()
        let viewController = CarDetailsViewController(withViewModel: viewModel, router: router)
        router.viewController = viewController

        return viewController
    }
}
```

And then the `CarDetailsViewModel` prepares displayable data for the `CarDetailsViewController` as it always does.

Thanks again for your question! I'll add this to the README.md to make it more visible.

**Comment by ETmanwenhan** [comment]
@pixeldock 
I have one more question: so how do you pass CarDetails data to CarList?

**Comment by pixeldock** [comment]
Sure. I can think of two scenarios:

**Use a data store**  
Example: The user can mark a car as `favorite` on the details page and then that car should be marked as favorite on the list as well, when the user goes back to the list.

What I would do:
1. the `CarDetailsModel` stores the favorite state of the car in your app's data store (e.g. CoreData, Realm).
2. when the `CarDetailsViewController` is popped and the `CarListViewController` becomes active again, it asks the `CarListViewModel` to refresh the car list data (and reload the list when the view model provides the new displayable data.

This would be my preferred option.

**Use a `CarDetailsDelegate` protocol**  
If you really have to pass data back to the list before popping the details ViewController you could use a delegate:

``` 
protocol CarDetailsDelegate: class {
    func carDetailsViewController(_ viewController: CarDetailsViewController, userDidAddCarToFavorites: Bool)
}
```
Then, before popping the details view controller you call that method on its `delegate` (which is the `CarListViewController`).

But, again, I think the first option is the better one. I cannot think of a scenario were I would use the delegate option.
