### ISSUE TITLE
Scene Builder

### ISSUE THREAD

**Issue by dimohamdy** [pixeldock/RxSwift-Xcode-Templates#3]
How can I use Scene builder with storyboard?

**Comment by pixeldock** [comment]
Thanks for your message! Can you describe a bit more in detail what you want to do?

**Comment by dimohamdy** [comment]
@pixeldock  I want to load Viewcontroller from StoryBoard but this prevents me from using Builder and set modelview how I can make this?

**Comment by pixeldock** [comment]
@dimohamdy You're right you cannot use the Builder concept as it is to load ViewControllers in Storyboards.

I have not tried that but my first idea would be to load the **ViewController** normally via Storyboard and then in `init(coder:)` ask the Builder for a **ViewModel** and a **Router** for that **ViewController**. Of course you would have to add those two getters to the Builder class. 

I don't know it that's a way to go for you, but that would be my approach.
